# Generated by Django 4.1.1 on 2022-09-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
