# Generated by Django 4.1.1 on 2022-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dis_price',
            field=models.IntegerField(blank=True),
        ),
    ]
