# Generated by Django 4.1.1 on 2022-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_dis_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dis_price',
            field=models.IntegerField(null=True),
        ),
    ]
