# Generated by Django 4.1.1 on 2022-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_discription_alter_item_dis_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='off_percentage',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
